id = "0x96f"
name = "0x96f Theme"
version = "1.1.1"
schema_version = 1
authors = ["Filip Janevski <filip@janevski.dev>"]
description = "A simple and pleasant dark theme for Zed"
repository = "https://github.com/filipjanevski/zed-theme"
